server:
  port: 9000
spring:
  application:
    name: test
  profiles: dev


mybatis-plus:
  # 配置扫描xml
  mapper-locations:
    - classpath:mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.jason.entity
  # 检测mybatis配置文件是否存在
  check-config-location: false
  configuration:
    # 驼峰装换
    map-underscore-to-camel-case: true

  global-config:
    # 刷新mapper文件修改 用于开发环境
    refresh: true
    # 逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1






